extends Node

const LIFE = "LIFE"
const MANA = "MANA"
const ARMOUR = "ARMOUR"
const EVASION = "EVASION"
const ACCURACY = "ACCURACY"
const STRENGTH = "STRENGTH"
const INTELLIGENCE = "INTELLIGENCE"
const DEXTERITY = "DEXTERITY"
const BLOCK = "BLOCK"
const DODGE = "DODGE"
const CRIT_STRIKE_CHANCE = "CRIT_STRIKE_CHANCE"
const CRIT_STRIKE_MULTI = "CRIT_STRIKE_MULTI"
